# Generated by Django 5.2.6 on 2025-09-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitex', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
