# Generated by Django 5.2.6 on 2025-09-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitex', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlastcurrency',
            old_name='curencyfrom',
            new_name='currencyfrom',
        ),
        migrations.RenameField(
            model_name='userlastcurrency',
            old_name='curencyto',
            new_name='currencyto',
        ),
        migrations.AddField(
            model_name='userlastcurrency',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
