version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "accounts_steam"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_django:/var/lib/postgresql/data
  django:
    build: .
    container_name: django

    ports:
      - 8000:8000
    depends_on:
      - postgres



volumes:
  postgres_data_django:
    driver: local

